# ================================================================================
# R DATA STRUCTURE: STATE FILE PATHS MAPPING
# ================================================================================
# Generated by code audit of state cleaning scripts
# Date: 2026-01-XX
# 
# This file contains R named lists mapping state folder names to file paths
# found in the corresponding per-state cleaning scripts.
# 
# For dynamically built paths, templates use {state} as placeholder for full state name.
# ================================================================================

# --------------------------------------------------------------------------------
# B) R NAMED LISTS FOR DIAGNOSTICS CONSUMPTION
# --------------------------------------------------------------------------------

# State-specific file paths (literal paths found in each state's cleaning script)
state_file_paths_literal <- list(
  
  Arkansas = c(
    "Data/Raw/state_databases/Arkansas/TankStats_web.mdb",
    "Data/Processed/county_fips_codes.csv"
  ),
  
  Louisiana = c(
    "Data/Raw/state_databases/Louisiana/LA_record_request.xlsx",
    "Data/Processed/county_fips_codes.csv"
  ),
  
  Maine = c(
    # Note: Maine downloads from URLs, not local files
    # URL: "https://www.maine.gov/dep/ftp/tanks/tanks_owner_all_registered_tanks.txt"
    # URL: "https://www.maine.gov/dep/ftp/hoss/report_tank_involved.txt"
    # URL: "https://www.maine.gov/dep/ftp/hoss/spill_report.txt"
    # URL: "https://www.maine.gov/dep/ftp/hoss/spill_log.txt"
    "Data/Processed/Census_Geography/Maine_census_geography.csv"
  ),
  
  Michigan = c(
    "Data/Raw/state_databases/Michigan/UTK Master List 3-3-25.xlsx",
    "Data/Raw/Releases.csv"
  ),
  
  `New Jersey` = c(
    "Data/Raw/state_databases/New Jersey/New Jersey Tanks Data.csv",
    "Data/Raw/state_databases/New Jersey/New Jersey Facility Data.csv",
    "Data/Raw/Releases.csv"
  ),
  
  `New Mexico` = c(
    "Data/Raw/USTs.csv",
    "Data/Raw/Facilities.csv",
    "Data/Raw/state_databases/New Mexico"  # Directory with pattern matching
    # Pattern: files matching "rp_nfa_amount" and "sl_nfa_amount" (case-insensitive)
  ),
  
  Oklahoma = c(
    "Data/Raw/state_databases/Oklahoma"  # Directory with pattern matching
    # Pattern: CSV files matching "Tank|PST_Tank" and "Case|Release|PST_Case" (case-insensitive)
  ),
  
  Texas = c(
    # Note: Texas downloads from URLs, not local files
    # Base URL: "https://www.tceq.texas.gov/assets/public/admin/data/docs"
    # Files: "pst_fac.txt", "pst_fin_assur.txt", "pst_self_cert.txt", "pst_ust.txt", "pst_ust_comprt.txt"
    "Data/Raw/state_databases/Texas/TX_LUST.csv"
    # Census URLs (for population data):
    # "https://www2.census.gov/programs-surveys/popest/datasets/2010-2020/counties/totals/co-est2020-alldata.csv"
    # "https://www2.census.gov/programs-surveys/popest/datasets/2000-2009/counties/totals/co-est2009-alldata.csv"
    # "https://www2.census.gov/programs-surveys/popest/tables/1990-2000/intercensal/st-co/stch-icen%d.txt" (for years 1990-2000)
  ),
  
  Tennessee = c(
    "Data/Raw/state_databases/Tennessee/ust_all-tn-compartments.xlsx",
    "Data/Raw/state_databases/Tennessee/ust_all-tn-environmental-sites.xlsx",
    "Data/Raw/Facilities.csv",
    "Data/Raw/uszips.csv"
  ),
  
  Colorado = c(
    "Data/Raw/state_databases/Colorado/Regulated_Storage_Tanks_in_Colorado__Oil___Public_Safety_20250728.csv",
    "Data/Raw/state_databases/Colorado/Petroleum_Releases__Colorado_Oil___Public_Safety_20250728.csv"
  )
)

# --------------------------------------------------------------------------------
# EPA National File Templates
# --------------------------------------------------------------------------------

epa_file_templates <- list(
  # National files that EPA script reads
  national = c(
    "Data/Raw/USTs.csv",
    "Data/Raw/Facilities.csv",
    "Data/Raw/Releases.csv"
  ),
  
  # Per-state processing template
  # The EPA script filters national files by: state == state_name
  # where state_name is the full state name (e.g., "Alabama", "California")
  per_state_template = "Data/Raw/state_databases/{state}/{state_abbr}_Harmonized_UST_tanks.csv",
  
  # State filtering code snippet
  filter_code = "state_UST_full[state == state_name]",
  
  # States excluded from EPA processing (have custom scripts)
  excluded_states = c("Arkansas", "Louisiana", "Maine", "Michigan", "New Jersey", "New Mexico", "Oklahoma", "Texas"),
  
  # Output directory template
  output_dir_template = "Data/Raw/state_databases/{state}",
  
  # Output file templates
  output_ust_template = "{state_abbr}_Harmonized_UST_tanks.csv",
  output_lust_template = "{state_abbr}_Harmonized_LUST.csv"
)

# --------------------------------------------------------------------------------
# Database Connection Patterns (for Access DBs)
# --------------------------------------------------------------------------------

db_connection_patterns <- list(
  Arkansas = list(
    db_path_template = "Data/Raw/state_databases/Arkansas/TankStats_web.mdb",
    connection_string_template = "Driver={Microsoft Access Driver (*.mdb, *.accdb)};Dbq={db_path};",
    tables = c(
      "TempRFACS_CountryNO",
      "TempTankStats_UG",
      "TempRLUSTLOG1"
    )
  )
)

# --------------------------------------------------------------------------------
# URL-based Data Sources
# --------------------------------------------------------------------------------

url_data_sources <- list(
  Maine = list(
    base_url = "https://www.maine.gov/dep/ftp",
    files = c(
      "tanks/tanks_owner_all_registered_tanks.txt",
      "hoss/report_tank_involved.txt",
      "hoss/spill_report.txt",
      "hoss/spill_log.txt"
    )
  ),
  Texas = list(
    base_url = "https://www.tceq.texas.gov/assets/public/admin/data/docs",
    files = c(
      "pst_fac.txt",
      "pst_fin_assur.txt",
      "pst_self_cert.txt",
      "pst_ust.txt",
      "pst_ust_comprt.txt"
    ),
    census_urls = c(
      "https://www2.census.gov/programs-surveys/popest/datasets/2010-2020/counties/totals/co-est2020-alldata.csv",
      "https://www2.census.gov/programs-surveys/popest/datasets/2000-2009/counties/totals/co-est2009-alldata.csv",
      "https://www2.census.gov/programs-surveys/popest/tables/1990-2000/intercensal/st-co/stch-icen%d.txt"
    )
  )
)

# --------------------------------------------------------------------------------
# Pattern-based File Discovery
# --------------------------------------------------------------------------------

pattern_based_files <- list(
  `New Mexico` = list(
    directory = "Data/Raw/state_databases/New Mexico",
    patterns = c(
      "rp_nfa_amount",  # Case-insensitive grep pattern
      "sl_nfa_amount"   # Case-insensitive grep pattern
    )
  ),
  Oklahoma = list(
    directory = "Data/Raw/state_databases/Oklahoma",
    patterns = c(
      "Tank|PST_Tank",      # Case-insensitive grep pattern for tank files
      "Case|Release|PST_Case"  # Case-insensitive grep pattern for LUST files
    ),
    file_extension = "\\.csv$"
  )
)

# --------------------------------------------------------------------------------
# Helper Function to Resolve Templates
# --------------------------------------------------------------------------------

# Example usage:
# resolve_epa_template(epa_file_templates$per_state_template, state_name = "Alabama")
# Returns: "Data/Raw/state_databases/Alabama/AL_Harmonized_UST_tanks.csv"
resolve_epa_template <- function(template, state_name) {
  # Convert state name to abbreviation
  state_abbr <- state.abb[match(state_name, state.name)]
  if(is.na(state_abbr)) {
    state_abbr <- toupper(substring(state_name, 1, 2))
  }
  
  # Replace placeholders
  result <- gsub("\\{state\\}", state_name, template)
  result <- gsub("\\{state_abbr\\}", state_abbr, result)
  
  return(result)
}

# ================================================================================
# END OF R DATA STRUCTURE
# ================================================================================
